/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EvaluacionRouteImport } from './routes/evaluacion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeccionIndexRouteImport } from './routes/leccion.$index'
import { Route as LeccionRouteImport } from './routes/leccion.'

const EvaluacionRoute = EvaluacionRouteImport.update({
  id: '/evaluacion',
  path: '/evaluacion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeccionIndexRoute = LeccionIndexRouteImport.update({
  id: '/leccion/$index',
  path: '/leccion/$index',
  getParentRoute: () => rootRouteImport,
} as any)
const LeccionRoute = LeccionRouteImport.update({
  id: '/leccion/',
  path: '/leccion/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evaluacion': typeof EvaluacionRoute
  '/leccion/': typeof LeccionRoute
  '/leccion/$index': typeof LeccionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evaluacion': typeof EvaluacionRoute
  '/leccion': typeof LeccionRoute
  '/leccion/$index': typeof LeccionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evaluacion': typeof EvaluacionRoute
  '/leccion/': typeof LeccionRoute
  '/leccion/$index': typeof LeccionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/evaluacion' | '/leccion/' | '/leccion/$index'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/evaluacion' | '/leccion' | '/leccion/$index'
  id: '__root__' | '/' | '/evaluacion' | '/leccion/' | '/leccion/$index'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvaluacionRoute: typeof EvaluacionRoute
  LeccionRoute: typeof LeccionRoute
  LeccionIndexRoute: typeof LeccionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/evaluacion': {
      id: '/evaluacion'
      path: '/evaluacion'
      fullPath: '/evaluacion'
      preLoaderRoute: typeof EvaluacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leccion/$index': {
      id: '/leccion/$index'
      path: '/leccion/$index'
      fullPath: '/leccion/$index'
      preLoaderRoute: typeof LeccionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leccion/': {
      id: '/leccion/'
      path: '/leccion'
      fullPath: '/leccion/'
      preLoaderRoute: typeof LeccionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvaluacionRoute: EvaluacionRoute,
  LeccionRoute: LeccionRoute,
  LeccionIndexRoute: LeccionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
